name: Deploy to cPanel
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, gd, zip, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'

      - name: Install NPM Dependencies & Build Assets
        run: |
          npm install
          npm run build

      # - name: Create .env file
      #   run: |
      #     cp .env.example .env
      #     php artisan key:generate --force
      #     sed -i "s/APP_ENV=local/APP_ENV=production/" .env
      #     sed -i "s/APP_DEBUG=true/APP_DEBUG=false/" .env

      - name: Prepare Storage Directories
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      - name: Cache Config
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_ROOT_DIR }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .env
            .env.example
            phpunit.xml
            package-lock.json
            tests/**
          log-level: verbose

      - name: Post-Deploy Permissions Fix
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd ${{ secrets.FTP_ROOT_DIR }}
            mkdir -p storage/framework/cache
            mkdir -p storage/framework/sessions
            mkdir -p storage/framework/views
            mkdir -p storage/logs
            chmod -R 775 storage
            chmod -R 775 bootstrap/cache
